apiVersion : apps/v1
kind: Deployment
metadata:
  name: fdlcloudhelloworldprivate 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdlcloudhelloworldprivate
  template:
    metadata:
      labels:
        app: fdlcloudhelloworldprivate 
    spec:
      containers:
        - name: fdlcloudhelloworldprivate 
          image: shelfv0.azurecr.io/fdlcloudhelloworldprivate
          ports:
          - containerPort: 80